### PR TITLE
workaround for BadToken.transfer

### PR DESCRIPTION
**Pull request by Velenir**
Adds `safeTranfer` function for tokens that implement ERC20 but with `transfer/transferFrom` functions not returning `bool`

### CODE REVIEW

**Comment by Velenir** [comment]
Check by reverting and reinstating changes in `DutchExchange.sol` and running
```
npx truffle test test/dutchExchange-depositWithdrawBadToken.js
```

**Comment by anxolin** [comment]
I'll merge to `release/2.0`, but @josojo it's good to have also your approval. This PR is to address a security concern that would get tokens stuck in case the ERC20 implementation is not correct (no return the success of the operation) 

More info here: https://medium.com/coinmonks/missing-return-value-bug-at-least-130-tokens-affected-d67bf08521ca

**Comment by anxolin** [comment]
Checked that we also can deploy the contracts to rinkeby with this version ;)

**Comment by anxolin** [comment]
I agree with @josojo, at the same time we start using their abstractions for the tokens, we should use the "standard utils" they provide, like math, or safe transfers

Thanks for the review

**Pull request merged**
